# This file contains the Conda environment configuration for running stdpopsim
# in a Dockerized image on Binder, accessible through https://mybinder.org/.
# Binder enables any Jupyter notebooks in the repository to be run interactively and
# reproducibly in a stable cloud-based environment.
#
# Developer Note: New Jupyter notebooks that are added to this repository should confirm
# that any package dependencies are specified in the list below.

name: stdpopsim-environment
channels:
        - conda-forge
        - bioconda
dependencies:
        - python=3.10
        - pip
        - git
        - numpy
        - pandas
        - jupyter
        - jupyterlab
        - ipywidgets
        - ipython
        - msprime
        - seaborn
        - scikit-allel
        - matplotlib
        - progressbar

        - pip:
                  - git+https://github.com/popsim-consortium/stdpopsim.git
